# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IncidentInfo
                                 A QGIS plugin
 This plugin provides information about an incident
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-03-21
        copyright            : (C) 2020 by WDA
        email                : mharchambault@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IncidentInfo class from file IncidentInfo.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .incident_info import IncidentInfo
    return IncidentInfo(iface)
